const K_DAYS='berrypay_v9_days',K_SET='berrypay_v9_settings',K_PIN='berrypay_v9_pin',K_LANG='berrypay_v9_lang';
const D={ru:{nextPay:'Ожидает выплаты',currentWeek:'Текущая неделя',today:'Сегодня',addShift:'Добавить смену',date:'Дата',field:'Поле',supervisor:'Вайзер',start:'Начало',end:'Конец',standard:'Стандарт',rubbish:'Рабиш',kg:'Килограммы',note:'Заметка',calculate:'Рассчитать',save:'Сохранить',calendar:'Календарь',days:'Дни',history:'История',stats:'Статистика',proof:'Проверка зарплаты',paidAmount:'Сколько пришло?',check:'Проверить',settings:'Настройки',rate:'Ставка £/час',ot:'Овертайм £/час',norm:'Норма кг',bonus:'Бонус за кг £',standardWeight:'Вес стандарта',rubbishWeight:'Вес рабиш',saveSettings:'Сохранить настройки',downloadCsv:'Скачать CSV',changePin:'Сменить PIN',clear:'Очистить данные',navHome:'Главная',navWeek:'Неделя',navHistory:'История',navStats:'Стат.',navProof:'Проверка',navSettings:'Настройки'},en:{nextPay:'Pending payment',currentWeek:'Current week',today:'Today',addShift:'Add shift',date:'Date',field:'Field',supervisor:'Supervisor',start:'Start',end:'End',standard:'Standard',rubbish:'Rubbish',kg:'Kilograms',note:'Note',calculate:'Calculate',save:'Save',calendar:'Calendar',days:'Days',history:'History',stats:'Stats',proof:'Pay check',paidAmount:'Amount received?',check:'Check',settings:'Settings',rate:'Rate £/hour',ot:'Overtime £/hour',norm:'Norm kg',bonus:'Bonus per kg £',standardWeight:'Standard weight',rubbishWeight:'Rubbish weight',saveSettings:'Save settings',downloadCsv:'Download CSV',changePin:'Change PIN',clear:'Clear data',navHome:'Home',navWeek:'Week',navHistory:'History',navStats:'Stats',navProof:'Check',navSettings:'Settings'},kg:{nextPay:'Төлөм күтүлүүдө',currentWeek:'Учурдагы апта',today:'Бүгүн',addShift:'Смена кошуу',date:'Дата',field:'Поле',supervisor:'Вайзер',start:'Башталышы',end:'Аягы',standard:'Стандарт',rubbish:'Рабиш',kg:'Килограмм',note:'Эскертүү',calculate:'Эсептөө',save:'Сактоо',calendar:'Календарь',days:'Күндөр',history:'Тарых',stats:'Статистика',proof:'Айлык текшерүү',paidAmount:'Канча түштү?',check:'Текшерүү',settings:'Жөндөө',rate:'Ставка £/саат',ot:'Овертайм £/саат',norm:'Норма кг',bonus:'1 кг бонус £',standardWeight:'Стандарт салмагы',rubbishWeight:'Рабиш салмагы',saveSettings:'Жөндөөлөрдү сактоо',downloadCsv:'CSV жүктөө',changePin:'PIN өзгөртүү',clear:'Маалыматты өчүрүү',navHome:'Башкы',navWeek:'Апта',navHistory:'Тарых',navStats:'Стат.',navProof:'Текшерүү',navSettings:'Жөндөө'}};
function L(){return localStorage.getItem(K_LANG)||'ru'} function t(k){return D[L()][k]||D.ru[k]||k}
function applyLang(){langBtn.textContent=L().toUpperCase();document.querySelectorAll('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));}
function changeLang(){let a=['ru','en','kg'];localStorage.setItem(K_LANG,a[(a.indexOf(L())+1)%3]);applyLang();renderAll()}
function toast(x){let e=document.getElementById('toast');e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
let pinBuf='';function dots(){document.querySelectorAll('.dots i').forEach((e,i)=>e.classList.toggle('on',i<pinBuf.length));pinTitle.textContent=localStorage.getItem(K_PIN)?'Enter PIN':'Create PIN'}
function pin(n){pinBuf+=n;if(pinBuf.length>4)pinBuf=pinBuf.slice(0,4);dots();if(pinBuf.length==4){let s=localStorage.getItem(K_PIN);if(!s){localStorage.setItem(K_PIN,pinBuf);unlock()}else if(s==pinBuf){unlock()}else{toast('Wrong PIN');pinBuf='';dots()}}}
function backPin(){pinBuf=pinBuf.slice(0,-1);dots()} function resetPin(){localStorage.removeItem(K_PIN);pinBuf='';document.getElementById('lock').classList.add('show');dots()} function unlock(){document.getElementById('lock').classList.remove('show');pinBuf='';dots()}
function setts(){return JSON.parse(localStorage.getItem(K_SET))||{rate:12.71,otRate:19.07,normKg:48,bonusKg:.75,standardKg:1.5,rubbishKg:4}}
function saveSettings(){let s={rate:+rate.value||12.71,otRate:+otRate.value||19.07,normKg:+normKg.value||48,bonusKg:+bonusKg.value||.75,standardKg:+standardKg.value||1.5,rubbishKg:+rubbishKg.value||4};localStorage.setItem(K_SET,JSON.stringify(s));toast('Saved');renderAll()}
function loadSettings(){let s=setts();rate.value=s.rate;otRate.value=s.otRate;normKg.value=s.normKg;bonusKg.value=s.bonusKg;standardKg.value=s.standardKg;rubbishKg.value=s.rubbishKg}
function days(){return JSON.parse(localStorage.getItem(K_DAYS))||[]} function setDays(x){localStorage.setItem(K_DAYS,JSON.stringify(x))}
function money(n){return '£'+(Math.round((n||0)*100)/100).toFixed(2)} function hm(h){let m=Math.round((h||0)*60);return Math.floor(m/60)+'ч '+m%60+'м'} function iso(d){return d.toISOString().slice(0,10)} function parse(v){let [h,m]=v.split(':').map(Number);return h*60+m}
function weekStart(d){d=new Date(d);let day=d.getDay(),diff=day>=5?day-5:day+2;d.setDate(d.getDate()-diff);d.setHours(0,0,0,0);return d}
function week(off){let st=weekStart(new Date(date.value||new Date()));st.setDate(st.getDate()+off*7);let en=new Date(st);en.setDate(st.getDate()+6);let ds=days().filter(x=>x.date>=iso(st)&&x.date<=iso(en));return{st,en,ds}}
function payDate(w){let d=new Date(w.en);d.setDate(d.getDate()+8);return d}
function autoKg(){let s=setts();kg.value=((+standard.value||0)*s.standardKg+(+rubbish.value||0)*s.rubbishKg).toFixed(2)}
function calc(){let s=setts(),sm=parse(start.value),em=parse(end.value);if(em<sm)em+=1440;let br=0;if(sm<480&&em>480)br+=15;if(sm<660&&em>660)br+=30;let h=Math.max((em-sm-br)/60,0),nh=Math.min(h,8),oh=Math.max(h-8,0),kgv=+kg.value||0,extra=Math.max(kgv-s.normKg,0),hourPay=nh*s.rate+oh*s.otRate,bonus=extra*s.bonusKg;return{date:date.value,field:fieldName.value||'',supervisor:supervisor.value||'',start:start.value,end:end.value,standard:+standard.value||0,rubbish:+rubbish.value||0,kg:kgv,h,oh,hourPay,bonus,total:hourPay+bonus,note:note.value||''}}
function mini(label,val,hot=''){return `<div class="mini ${hot}"><span>${label}</span><b>${val}</b></div>`}
function preview(){let r=calc();previewBox.innerHTML=mini('Hours',hm(r.h))+mini('Overtime',hm(r.oh))+mini('Bonus',money(r.bonus))+mini('Total',money(r.total),'hot');todayBox.innerHTML=mini(t('field'),r.field||'-')+mini(t('supervisor'),r.supervisor||'-')+mini(t('kg'),r.kg+' кг')+mini(t('today'),money(r.total),'hot');return r}
function saveDay(){let r=preview();if(!r.date)return toast('Date?');let d=days().filter(x=>x.date!==r.date);d.push(r);d.sort((a,b)=>a.date.localeCompare(b.date));setDays(d);toast('Saved');renderAll()}
function renderAll(){applyLang();let cur=week(0),prev=week(-1),pt=prev.ds.reduce((a,b)=>a+b.total,0),ct=cur.ds.reduce((a,b)=>a+b.total,0);pendingPay.textContent=money(pt);weekMoney.textContent=money(ct);pendingRange.textContent=iso(prev.st)+' → '+iso(prev.en);weekRange.textContent=iso(cur.st)+' → '+iso(cur.en);pendingDate.textContent='Payday: '+iso(payDate(prev));renderCalendar(cur);renderLists(cur);renderStats();if(!todayBox.innerHTML)todayBox.innerHTML=mini(t('field'),'-')+mini(t('supervisor'),'-')+mini(t('kg'),'0 кг')+mini(t('today'),money(0),'hot')}
function renderCalendar(w){let worked=new Set(w.ds.map(x=>x.date)),today=iso(new Date()),html='';for(let i=0;i<7;i++){let d=new Date(w.st);d.setDate(w.st.getDate()+i);let id=iso(d);html+=`<div class="day ${worked.has(id)?'worked':''} ${id==today?'today':''}">${id.slice(8)}</div>`}calendar.innerHTML=html}
function renderLists(w){weekList.innerHTML=w.ds.length?w.ds.map(x=>`<div class="row"><div><b>${x.date}</b><div class="muted">📍 ${x.field||'-'} · 👨‍🌾 ${x.supervisor||'-'}<br>${x.start}-${x.end} · ${x.standard} ст · ${x.rubbish} раб · ${x.kg} кг</div></div><b>${money(x.total)}</b></div>`).join(''):'<p class="muted">Empty</p>';let map={};days().forEach(x=>{let k=iso(weekStart(new Date(x.date)));map[k]=(map[k]||0)+x.total});historyList.innerHTML=Object.entries(map).reverse().map(([k,v])=>`<div class="row"><b>${k}</b><b>${money(v)}</b></div>`).join('')||'<p class="muted">Empty</p>'}
function renderStats(){let ds=days(),sum=k=>ds.reduce((a,b)=>a+(b[k]||0),0),best=ds.length?Math.max(...ds.map(x=>x.total)):0;statsBox.innerHTML=mini('Days',ds.length)+mini('Kg',sum('kg').toFixed(1))+mini('Hours',hm(sum('h')))+mini('Best',money(best),'hot')}
function checkPay(){let prev=week(-1),should=prev.ds.reduce((a,b)=>a+b.total,0),paid=+paidAmount.value||0,diff=paid-should;let daysHtml=prev.ds.map(x=>`<div class="proofDay"><b>${x.date} — ${money(x.total)}</b><div class="muted">📍 ${x.field||'-'} · 👨‍🌾 ${x.supervisor||'-'}<br>${x.start}-${x.end} · ${x.kg} кг · ${x.standard} ст · ${x.rubbish} раб</div></div>`).join('');proofResult.innerHTML=`<div class="statsGrid">${mini('Should be',money(should),'hot')}${mini('Paid',money(paid))}${mini('Difference',money(diff))}${mini('Days',prev.ds.length)}</div>${daysHtml}`;}
function tab(id,b){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAll()}
function clearAll(){if(confirm('Delete all?')){localStorage.removeItem(K_DAYS);renderAll()}}
function exportCSV(){let csv='Date,Field,Supervisor,Start,End,Standard,Rubbish,Kg,Hours,Overtime,Total,Note\n';days().forEach(x=>csv+=[x.date,x.field,x.supervisor,x.start,x.end,x.standard,x.rubbish,x.kg,x.h.toFixed(2),x.oh.toFixed(2),x.total.toFixed(2),`"${x.note||''}"`].join(',')+'\n');let blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='berrypay-report.csv';a.click();URL.revokeObjectURL(url)}
date.value=new Date().toISOString().slice(0,10);loadSettings();applyLang();renderAll();dots();if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));}